services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: newsai # Adaptez le nom de l'image si vous le souhaitez
    container_name: newsai # Adaptez le nom du conteneur si vous le souhaitez
    ports:
      - "3002:3000"
    env_file:
      - .env.production.local
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
