services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: newsai
    container_name: newsai
    ports:
      - "3002:3000"
    env_file:
      - .env.production.local
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"